message: ENC[AES256_GCM,data:kl7UmYxGaAc=,iv:IzBFa3RFmuZIvAdd5QfOWO1mypg2pJCt3xsCnrjrlII=,tag:tXIdX7c9lQbVYqSrtvhsQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-12T13:23:46Z"
    mac: ENC[AES256_GCM,data:7dbUsvylqFLwPFB9lJ2dIIfZsvk2V3EvbpfhZlsNVwzJdQ3Ryh9sidDmnNYoZn+oKtW0LxkvmAqjKK+ucSfrV2vkWsVoj47vwdH+n70Q+A7scOq48u+JMkAI6oqfyxlPDUxjGUn4wlzT+cBv8LQooqUS9lor1/fyitlbM4lWt+o=,iv:wLFclt8h55oDulYbZ3YW2Y6DEG5tgA/lKWuTdCY9iug=,tag:mKTHfJztx1T7hUSB8+fTXQ==,type:str]
    pgp:
        - created_at: "2023-12-12T13:23:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA4ZVmAdnTXtXAQv9FR8GGdNbYI9NUXojIXjCTQDJaqUa7YwkajMqrva7L01s
            bGuaMVfMhaQaW8KL3ktnqCVkWXkMxmXghiZDyEHtVdLmxLUAKyP24xFACb3SJAdj
            r2e7EaS2l9Cw4p/v0lHtBwJ67rgqqTtN20kttX30RB8thgU2lW9u5c8re3TqkMKe
            bmxcV9aluUN563fwPaoHvMwMRjp0hHl4h7gobfO5e9KoC70hxJOS4ctM848A56zk
            FRrcXmcmkVMgouGxed0hmqX/CL43P9g4AyvYTVgIU4ymRRV5nIYGLHvvkYhmnhbt
            83tf2eYxUZfvlwS1+STNg5lacjZ2g+d/855qBlyvfApdM7Xv7D20MgE0vdi0n3nP
            en/Dc0dWvT2IYvaqoLbSPpg9kQoQmlUQaK+aUkOf3k+r6f2IJBFYVstjXqZxRrUJ
            4tcNEnwHvNDL2E6YqEcTwFSXGIKNSqryjI9g0lJTzn8D20Is1BGGgTRU6fUnOD7Z
            pxEs8kuKcBsm09E2NdUa0l4B10aPT04v2IXaareLOGkmYPLEY5gQsrOctT0sLZC5
            uO3tJPcVxLYN82qARZhaNv0INllRItJ/v3ECEytnm9vrk+eJT3Ad+LtsuBPwqSKF
            5k7p95YHR/GcguFr4jiV
            =mqYG
            -----END PGP MESSAGE-----
          fp: FA0265F68B91238B8D44B0EA552049CBD345A831
        - created_at: "2023-12-12T13:23:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA3JxZ2AkFo1uAQwAidO7EjAJewuNbgaH13IeoOJqJYjNqaXeH/41jlzDlDNq
            YFlj49LdP6MTYbngjELTBkXl9bnwilZ5TtNjVwf5TYtBcHI2gZNZDU4XL1QdPqo+
            5yKfCDoJZVwa5yt1gzlssh+9WqcyN2HQ5aKm/xN2ikiuHkGNlRpnDwMHOhBaXERw
            r9MIPF6/nzzNVubej1Vh3OkJMzXXwoEylnzxq/DCNs96WEKF88vEK9um1HBzShM8
            x2ZoWUgzHWEf2FSBSGYbseRiB4SCAl4GskbtFQyZguPe4GX7YMhJ+BuXrznXA97M
            Nau5V1zZsOVV7A8uTHS9QdYDgWc3/VvkRpxJ2GzKIcEKSxwwXtfymnOBfWSgopyM
            ZipgqUrXw/LV+GSoD9+bonLsj0tiliqdYnu5JUGP7gb2KzJIYYygH5roHGqwhuwr
            /ptBZUeRuMDvZyt4lh+ktXIELaEq4xissKWbSymIk/ZNBKB8fcynLS2S/AjUxnAl
            71954o9DnwO0Tsg8BXpH0l4BWciDm3kaGb7AxbKxpmoVk7wcoF5YTmFMx43UK6XJ
            R81Ry9aNVZS7Oz9S0hTJvYdkLR2VHGYWhSnnQfCSZduoQDzkW0skTMq7lswgrr0w
            LWuSkH9cpL8plxuLRj/J
            =LExq
            -----END PGP MESSAGE-----
          fp: D14083ABCA90CBB0A3164C0D1B7419E32C7947A6
    unencrypted_suffix: _unencrypted
    version: 3.7.3
