message: ENC[AES256_GCM,data:mu1MKYskrIhm,iv:DIZO2N1YZ6eA9VVxrQGX/S/BbcX/ZHzGs5FVngVHDUA=,tag:ChNE3TDuQfibs5Xj0abk3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-12T13:23:50Z"
    mac: ENC[AES256_GCM,data:y6Y7QXtcYf4amZhEXWjCnSnO12rpUZBttIxHLKqT4oVks4WcllB6zsRzzhIpalKrrEgXegs6J5weKcUJhr8b9Uo73nk1EtzaekUdAV/QywGkkAmRzYuOAlPaTiNIkqSbRGam6b74/pWYQ41PW3df5PIsszGq2YweMg2cPsq9Iz4=,iv:h9VtENkBvaF1tlJnt/VKozBJLRxAGcnt50oPwG6WKqg=,tag:j9McNeefmpvjWp0I7kPtOg==,type:str]
    pgp:
        - created_at: "2023-12-12T13:23:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA4ZVmAdnTXtXAQv/cFA+pixvWm4MwUrddHShfk9k4V2RSCe8ku9Hx5qvymoG
            fLXJMe8QqYy779dJopTg1RgPZ7IVVrt15RsJaXp2TnfTSFIRcHTNNrnIyNIUe9Mn
            6rvSY27g1hidMdtp8KNeDyZ0RDONfq7uYLM9XHLugzN0egJceQc8kWeAMTQZnEE5
            CsI/iFH3zq2a3Fl83FPDYoOF5I2FChWE66b9pV8UK9GkcHin9Kl6A/8DIxPUZLPw
            IwayVIp/dTdARSKpPak09TG1qyCulp+YwQt29w+0O6+4cecsxslv+oz0m2pqExvR
            arErcWcZGd7vWeqZC824KwhieLSMqlj+CWJckajV17OXPczCRsE6vLLbfh//t2/l
            DSCQ8kBITMq+sEgWHGsTLPrPgfQdW5S3oFIxItG8HiIbk9fBQZtSgGBOPnNJ6IJ9
            Hi+5DZwY8C8dnWEq73AeMrbRqcuX/CXwRBJXG9QJf/l6hFhp9E5GfKx72yvonm0E
            PPLB3Nr03wQkCEyiR55/0lwBasdp6GS0O16bb3giv2cuRqdP639boRVK3NakXcjf
            tvVbSCCgHzxMOm7FvbjLZIIcstEoadXDUwaJrsVxurQHw9tkvV+B4Nvrmk6Nhhb6
            NpPO9lzMbfsh1DEjGw==
            =9U1I
            -----END PGP MESSAGE-----
          fp: FA0265F68B91238B8D44B0EA552049CBD345A831
        - created_at: "2023-12-12T13:23:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA3JxZ2AkFo1uAQv/ToGRl9155M7zeY67gYi8d2MOPNJreOIcLJQL7QBAUPMm
            hddfmF6wp0A3ZZI2sg0NCWcwMFkGXSkObK+sW/BuhbOdYV6QiyY6vxzLyCtm/mwA
            ON47fIxkIxiloIzsgOV992QKucbvev8f4awWgNr3HRPITeGW7EGL6MMfhMwQRXpS
            x42g83A6ViEu32RnmlGw2mxVAkLveKDsGfRYZCZ4zU/9grUTmB0UfiH4Wi+RCbiQ
            YHlagau5tqTMPpIGE8HPybpWUanp5XZAtS56Surn5KKbKnVgpKgH2moSeGFLX81Q
            DwFpKdcPGcyT4xPMYbcn+PYfkgJxS3EKgld6gaDDpgnWSXnfO8hffWKyWpoYmRyi
            t3SnEvoOV5KpS7BDgl4lsC9mnY85ftUCdc63qLMfEciapCeaBK0P/kFpoXGN5ja2
            /3gkw19aMPwvGj5hXpkoG0f7kZYFY1PlMgO/8YkOss+3gOQthvprwvkifgmmcMXi
            YliDNV/mErE02cgxsygQ0lwBmDV/8kyeHMx97P2fqOE45S2sFU/vnfDXNQGy1rza
            TzYE1vZEhojmDY1XlLDZMoaVUZc0ZvsBk5KF+eefQV73EMCuHT2g6UKhK7eWCOiH
            fEz2Saup6NT0y76nRg==
            =2iY5
            -----END PGP MESSAGE-----
          fp: D14083ABCA90CBB0A3164C0D1B7419E32C7947A6
    unencrypted_suffix: _unencrypted
    version: 3.7.3
