
# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  enabled: true
  hostname: demo.sme-long-running.a1ck.io
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

# Provide a custom message
message: test


service:
  type: ClusterIP
  port: 80

deployment:
  replicaCount: 3
  container:
    image:
      repository: "harbor.sme-long-running.a1ck.io/demo/hello-ck8s"
      tag: '1.10'
      pullPolicy: IfNotPresent
    port: 8080

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources:
    requests:
      memory: 32Mi
      cpu: 50m
    limits:
      memory: 64Mi
      cpu: 100m

  tolerations: []

  affinity: {}