name: Build-and-publish-image

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: harbor.pavgun-dev.a1ck.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/app/Dockerfile
          push: true
          tags: |
            harbor.pavgun-dev.a1ck.io/demo/hello-ck8s:${{ github.event.pull_request.head.sha }}
            harbor.pavgun-dev.a1ck.io/demo/hello-ck8s:${{ github.event.pull_request.head.ref }}
  update-tag:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout hello-ck8s
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "ci-bot@argocd.com"
          git config --global user.name "ci-bot"

      - name: Update image tag
        run: |
          git status
          sed -i "s,tag:.*,tag:\ ${{ github.event.pull_request.head.sha }}," deploy/helm/hello-ck8s/values.yaml
          git add deploy/helm/hello-ck8s/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git pull origin ${{ github.event.pull_request.head.ref }} --rebase
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.head_ref }}
  add_labels:
    runs-on: ubuntu-latest
    needs: update-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            deploy